/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challeng_6;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

//        LinkedList<Integer> numbers = new LinkedList();
//
//        numbers.Append(1);
//        numbers.Append(3);
//        numbers.Append(2);
//
//        System.out.println(numbers);
//
//        numbers.InsertBefore(3, 5);
//        System.out.println(numbers);
//
//        LinkedList<Integer> numbers1 = new LinkedList();
//
//        numbers1.Append(1);
//        numbers1.Append(3);
//        numbers1.Append(2);
//
//        numbers1.InsertAfter(3, 5);
//        System.out.println(numbers1);
    }
}
