/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge7;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.function.Executable;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void addOneLastTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        String res="{1} -> NULL";
        assertEquals(res,numbers.toString());
    }

    @Test void addLastTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        String res="{1} ->{3} ->{2} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void insertBeforeTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        numbers.InsertBefore(3, 5);
        String res="{1} ->{5} ->{3} ->{2} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void insertBeforeFirstTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        numbers.InsertBefore(1, 5);
        String res="{5} ->{1} ->{3} ->{2} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void insertAfterTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        numbers.InsertAfter(3, 5);
        String res="{1} ->{3} ->{5} ->{2} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void insertAfterLastTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        numbers.InsertAfter(2, 5);
        String res="{1} ->{3} ->{2} ->{5} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void KthTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(8);
        numbers.Append(2);
        assertEquals(3,numbers.Kth(2));
    }
    @Test void KgreaterThanLengthTest(){
        assertThrows(IllegalArgumentException.class, new Executable() {
            @Override
            public void execute() throws Throwable {
                LinkedList<Integer> numbers = new LinkedList<>();
                numbers.Append(1);
                numbers.Append(3);
                numbers.Append(8);
                numbers.Append(2);
                numbers.Kth(6);

            }
        });

    }

    @Test void sameValuesTest(){
        assertThrows(IllegalArgumentException.class, new Executable() {
            @Override
            public void execute() throws Throwable {
                LinkedList<Integer> numbers = new LinkedList<>();
                numbers.Append(1);
                numbers.Append(3);
                numbers.Append(8);
                numbers.Append(2);
                numbers.Kth(4);

            }
        });

    }
    @Test void NegativeValueTest(){
        assertThrows(IllegalArgumentException.class, new Executable() {
            @Override
            public void execute() throws Throwable {
                LinkedList<Integer> numbers = new LinkedList<>();
                numbers.Append(1);
                numbers.Append(3);
                numbers.Append(8);
                numbers.Append(2);
                numbers.Kth(-3);

            }
        });

    }
    @Test void SizeOneTest(){
        assertThrows(IllegalArgumentException.class, new Executable() {
            @Override
            public void execute() throws Throwable {
                LinkedList<Integer> numbers = new LinkedList<>();
                numbers.Append(1);
                numbers.Kth(0);

            }
        });

    }
}
