/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

import challenges.AnimalShelter.AnimalShelter;
import challenges.AnimalShelter.Cat;
import challenges.AnimalShelter.Dog;
import challenges.HashMap.Structure.HashMap;
import challenges.InsertionSort.InsertionSort;
import challenges.MergeSort.MergeSort;
import challenges.QuickSort.QuickSort;
import challenges.RepeatedWord.RepeatedWord;
import challenges.Trees.data.BTNode;
import challenges.Trees.structure.BinarySearchTree;
import challenges.Trees.structure.BinaryTree;
import challenges.pseudoQueue.pseudoQueue;
import challenges.queue.structure.Queue;
import challenges.stack.structure.Stack;
import challenges.validateBrackets.ValidateBrackets;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static challenges.Trees.structure.BinaryTree.TraversalOrder.*;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void stackPushTest(){
        Stack newStack=new Stack();
        newStack.push("1");
        assertEquals(1,newStack.getSize());
    }
    @Test void stackMultiplePushTest(){
        Stack newStack=new Stack();
        newStack.push("1");
        newStack.push("2");
        newStack.push("3");
        newStack.push("4");
        newStack.push("5");
        assertEquals(5,newStack.getSize());
    }
    @Test void stackPopTest() throws Exception {
        Stack newStack=new Stack();
        newStack.push("1");
        newStack.push("2");
        newStack.push("3");
        newStack.push("4");
        newStack.push("5");
        System.out.println(newStack.pop());
        assertEquals(4,newStack.getSize());
    }
    @Test void stackMultiplePopTest() throws Exception {
        Stack newStack=new Stack();
        newStack.push("1");
        newStack.push("2");
        newStack.push("3");
        newStack.push("4");
        newStack.push("5");
        System.out.println(newStack.pop());
        System.out.println(newStack.pop());
        System.out.println(newStack.pop());
        System.out.println(newStack.pop());
        System.out.println(newStack.pop());
        assertEquals(0,newStack.getSize());
    }
    @Test void stackPeekTest() throws Exception {
        Stack newStack=new Stack();
        newStack.push("1");
        newStack.push("2");
        newStack.push("3");
        newStack.push("4");
        newStack.push("5");
        System.out.println(newStack.peek());
        assertEquals("5",newStack.peek());
    }
    @Test void stackEmptyTest(){
        Stack newStack=new Stack();
        assertNull(newStack.getTop());
    }
    @Test void stackEmptyPopTest()  {
        assertThrows(Exception.class, () -> {
            Stack newStack=new Stack();
            newStack.pop();
        });
    }
    @Test void stackEmptyPeekTest(){
        assertThrows(Exception.class, () -> {
            Stack newStack=new Stack();
            String val=newStack.peek();
        });
    }
    @Test void queueEnqueueTest(){
        Queue<String> newQueue=new Queue<String>();
        newQueue.enqueue("1");
        assertEquals(1,newQueue.getSize());
    }
    @Test void queueEnqueueMultipleTest(){
        Queue<String> newQueue=new Queue<>();
        newQueue.enqueue("1");
        newQueue.enqueue("2");
        newQueue.enqueue("3");
        newQueue.enqueue("4");
        newQueue.enqueue("5");
        assertEquals(5,newQueue.getSize());
    }
    @Test void DequeueTest() throws Exception {
        Queue<String> newQueue=new Queue<String>();
        newQueue.enqueue("1");
        newQueue.enqueue("2");
        newQueue.enqueue("3");
        newQueue.enqueue("4");
        newQueue.enqueue("5");
        System.out.println(newQueue.dequeue());
        assertEquals(4,newQueue.getSize());
    }
    @Test void queuePeekTest() throws Exception {
        Queue<String> newQueue=new Queue<>();
        newQueue.enqueue("1");
        newQueue.enqueue("2");
        newQueue.enqueue("3");
        newQueue.enqueue("4");
        newQueue.enqueue("5");
        System.out.println(newQueue.peek());
        assertEquals("1",newQueue.peek());
    }
    @Test void DequeueMultipleTest() throws Exception {
        Queue<String> newQueue=new Queue<String>();
        newQueue.enqueue("1");
        newQueue.enqueue("2");
        newQueue.enqueue("3");
        newQueue.enqueue("4");
        newQueue.enqueue("5");
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.dequeue());
        assertEquals(0,newQueue.getSize());
    }
    @Test void EmptyQueueTest(){
        Queue<String> newQueue=new Queue<>();
        assertNull(newQueue.getFront());
    }
    @Test void queueEmptyPeekTest(){
        assertThrows(Exception.class, () -> {
            Queue<String> newQueue=new Queue<>();
            String val=newQueue.peek();
            System.out.println(val);
        });
    }
    @Test void queueEmptyDequeueTest(){
        assertThrows(Exception.class, () -> {
            Queue<String> newQueue=new Queue<>();
            String val=newQueue.dequeue();
            System.out.println(val);
        });
    }
    @Test void pseudoQueueTest() throws Exception {
        pseudoQueue newQueue=new pseudoQueue();
        newQueue.enQueue("1");
        newQueue.enQueue("2");
        newQueue.enQueue("3");
        newQueue.enQueue("4");

        assertEquals("1",newQueue.getS1().getTop().getValue());
    }
    @Test void pseudoDequeueTest() throws Exception {
        pseudoQueue newQueue=new pseudoQueue();
        newQueue.enQueue("1");
        newQueue.enQueue("2");
        newQueue.enQueue("3");
        newQueue.enQueue("4");
        String last=newQueue.deQueue();
        assertEquals("1",last);
    }

    @Test void animalShelterTest() throws Exception {
        AnimalShelter<String> animal=new AnimalShelter<>();
        animal.enQueue(new Cat<>("cat1"));
        animal.enQueue(new Dog<>("dog1"));
        animal.enQueue(new Cat<>("cat2"));
        animal.enQueue(new Dog<>("dog2"));
        animal.enQueue(new Cat<>("cat3"));

        assertEquals("cat1",animal.deQueue("cat").getValue());
    }
    @Test void animalShelterSizeTest() throws Exception {
        AnimalShelter<String> animal=new AnimalShelter<>();
        animal.enQueue(new Cat<>("cat1"));
        animal.enQueue(new Dog<>("dog1"));
        animal.enQueue(new Cat<>("cat2"));
        animal.enQueue(new Dog<>("dog2"));
        animal.enQueue(new Cat<>("cat3"));

        assertEquals(5,animal.getSize());
    }
    @Test void animalShelterEmptyTest() throws Exception {
        AnimalShelter<String> animal=new AnimalShelter<>();
        animal.enQueue(new Dog<>("dog1"));
        animal.enQueue(new Dog<>("dog2"));

        assertNull(animal.deQueue("cat"));
    }
    @Test void validateBracketsTrueTest(){
        String str="{}{Code}[Fellows](())";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(true,ob.validateBrackets(str));
    }
    @Test void validateBracketsTrue2Test(){
        String str="{}";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(true,ob.validateBrackets(str));
    }
    @Test void validateBracketsTrue3Test(){
        String str="{}(){}";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(true,ob.validateBrackets(str));
    }
    @Test void validateBracketsTrue4Test(){
        String str="()[[Extra Characters]]";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(true,ob.validateBrackets(str));
    }
    @Test void validateBracketsTrue5Test(){
        String str="(){}[[]]";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(true,ob.validateBrackets(str));
    }
    @Test void validateBracketsFalse1Test(){
        String str="[({}]";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(false,ob.validateBrackets(str));
    }
    @Test void validateBracketsFalse2Test(){
        String str=")";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(false,ob.validateBrackets(str));
    }
    @Test void validateBracketsFalse3Test(){
        String str="(](";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(false,ob.validateBrackets(str));
    }
    @Test void validateBracketsFalse4Test(){
        String str="{(})";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(false,ob.validateBrackets(str));
    }
    @Test void validateBracketsFalse5Test(){
        String str="{";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(false,ob.validateBrackets(str));
    }
    @Test void validateBracketsFalse6Test(){
        String str="[}";
        ValidateBrackets ob=new ValidateBrackets();
        assertEquals(false,ob.validateBrackets(str));
    }

    @Test void EmptyBinaryTreeTest(){
        BinaryTree<Integer> tre=new BinaryTree<>();
        assertNull(tre.getRoot());
    }
    @Test void BinaryTreeTest(){
        BinaryTree<Integer> tre=new BinaryTree<>(9);
        assertNotNull(tre.getRoot());
    }
    @Test void BinarySearchTreeLeftTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        assertEquals(4,newTree.getRoot().getLeftNode().getData());
    }
    @Test void BinarySearchTreeRightTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        assertEquals(8,newTree.getRoot().getRightNode().getData());
    }
    @Test void BinarySearchTreeRootTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        assertEquals(5,newTree.getRoot().getData());
    }
    @Test void BinarySearchTreeAddTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.getRoot().setLeftNode(new BTNode<Integer>(8) {
            @Override
            public int compareTo(BTNode<Integer> o) {
                return 0;
            }
        });
        newTree.getRoot().setRightNode(new BTNode<Integer>(4) {
            @Override
            public int compareTo(BTNode<Integer> o) {
                return 0;
            }
        });
        assertEquals(8,newTree.getRoot().getLeftNode().getData());
    }
    @Test void BinarySearchTreePreorderTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        newTree.add(3);
        newTree.add(4);
        newTree.add(90);
        newTree.add(55);
        assertEquals("[5, 4, 3, 8, 90, 55]",newTree.traverse(PREORDER).toString());
    }
    @Test void BinarySearchTreeInorderTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        newTree.add(3);
        newTree.add(4);
        newTree.add(90);
        newTree.add(55);
        assertEquals("[3, 4, 5, 8, 55, 90]",newTree.traverse(INORDER).toString());
    }
    @Test void BinarySearchTreePostorderTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        newTree.add(3);
        newTree.add(4);
        newTree.add(90);
        newTree.add(55);
        assertEquals("[3, 4, 55, 90, 8, 5]",newTree.traverse(POSTORDER).toString());
    }
    @Test void BinarySearchTreeContainsTrueTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        newTree.add(3);
        newTree.add(4);
        newTree.add(90);
        newTree.add(55);
        assertTrue(newTree.Contains(90));
    }
    @Test void BinarySearchTreeContainsFalseTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        newTree.add(3);
        newTree.add(4);
        newTree.add(90);
        newTree.add(55);
        assertFalse(newTree.Contains(9));
    }
    @Test void BinarySearchTreeSizeTest(){
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        newTree.add(3);
        newTree.add(4);
        newTree.add(90);
        newTree.add(55);
        assertEquals(6,newTree.getSize()); //it gives me 6 because binary search tree doesn't add redundant value
    }

    @Test void breadthFirstTest() throws Exception {
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();
        newTree.add(5);
        newTree.add(8);
        newTree.add(4);
        newTree.add(3);
        newTree.add(4);
        newTree.add(90);
        newTree.add(55);
        assertEquals("[5, 4, 8, 3, 90, 55]",newTree.breadthFirst().toString());
    }
    @Test void breadthFirstEmptyTest() throws Exception {
        BinarySearchTree<Integer> newTree=new BinarySearchTree<>();

        assertNull(newTree.breadthFirst());
    }
    @Test void maxTreeTest(){
        BinaryTree<Integer> maxTree=new BinaryTree<Integer>();
        BTNode<Integer> node1=new BTNode<Integer>(2);
        maxTree.setRoot(node1);

        node1.setLeftNode(new BTNode<Integer>(7));
        node1.setRightNode(new BTNode<Integer>(5));

        node1.getLeftNode().setLeftNode(new BTNode<Integer>(2));
        node1.getLeftNode().setRightNode(new BTNode<Integer>(6));

        node1.getLeftNode().getRightNode().setLeftNode(new BTNode<Integer>(5));
        node1.getLeftNode().getRightNode().setRightNode(new BTNode<Integer>(11));

        node1.getRightNode().setRightNode(new BTNode<Integer>(9));
        node1.getRightNode().getRightNode().setLeftNode(new BTNode<Integer>(4));

        assertEquals(11,maxTree.getMaxNum());
    }
    @Test void maxTreeEmptyTest(){
        BinaryTree<Integer> maxTree=new BinaryTree<Integer>();
        assertNull(maxTree.getMaxNum());
    }
    @Test void maxTreeOneNumTest(){
        BinaryTree<Integer> maxTree=new BinaryTree<Integer>();
        BTNode<Integer> node1=new BTNode<Integer>(2);
        maxTree.setRoot(node1);
        assertEquals(2,maxTree.getMaxNum());
    }

    @Test void maxTreeNegativeTest(){
        BinaryTree<Integer> maxTree=new BinaryTree<Integer>();
        BTNode<Integer> node1=new BTNode<Integer>(-2);
        maxTree.setRoot(node1);

        node1.setLeftNode(new BTNode<Integer>(-7));
        node1.setRightNode(new BTNode<Integer>(-5));

        node1.getLeftNode().setLeftNode(new BTNode<Integer>(-2));
        node1.getLeftNode().setRightNode(new BTNode<Integer>(-6));

        node1.getLeftNode().getRightNode().setLeftNode(new BTNode<Integer>(-5));
        node1.getLeftNode().getRightNode().setRightNode(new BTNode<Integer>(-11));

        node1.getRightNode().setRightNode(new BTNode<Integer>(-9));
        node1.getRightNode().getRightNode().setLeftNode(new BTNode<Integer>(-4));

        assertEquals(-2,maxTree.getMaxNum());
    }
    @Test void fizzbuzzTest(){
        BinaryTree<Integer> fizzbuzz=new BinaryTree<>();
        fizzbuzz.setRoot(new BTNode<>(5));
        fizzbuzz.getRoot().setLeftNode(new BTNode<>(4));
        fizzbuzz.getRoot().setRightNode(new BTNode<>(3));
        fizzbuzz.getRoot().getLeftNode().setLeftNode(new BTNode<>(15));
        fizzbuzz.getRoot().getLeftNode().setRightNode(new BTNode<>(9));
        fizzbuzz.getRoot().getRightNode().setLeftNode(new BTNode<>(6));
        fizzbuzz.getRoot().getRightNode().setRightNode(new BTNode<>(7));
        System.out.println(fizzbuzz.fizzbuzzTree(fizzbuzz));
        assertEquals("Buzz",fizzbuzz.fizzbuzzTree(fizzbuzz).getRoot().getData());
    }
    @Test void fizzbuzzLeftNodeTest(){
        BinaryTree<Integer> fizzbuzz=new BinaryTree<>();
        fizzbuzz.setRoot(new BTNode<>(5));
        fizzbuzz.getRoot().setLeftNode(new BTNode<>(4));
        fizzbuzz.getRoot().setRightNode(new BTNode<>(3));
        fizzbuzz.getRoot().getLeftNode().setLeftNode(new BTNode<>(15));
        fizzbuzz.getRoot().getLeftNode().setRightNode(new BTNode<>(9));
        fizzbuzz.getRoot().getRightNode().setLeftNode(new BTNode<>(6));
        fizzbuzz.getRoot().getRightNode().setRightNode(new BTNode<>(7));
        System.out.println(fizzbuzz.fizzbuzzTree(fizzbuzz));
        assertEquals("4",fizzbuzz.fizzbuzzTree(fizzbuzz).getRoot().getLeftNode().getData());
    }
    @Test void fizzbuzzNullTest(){
        BinaryTree<Integer> fizzbuzz=new BinaryTree<>();

        System.out.println(fizzbuzz.fizzbuzzTree(fizzbuzz));
        assertNull(fizzbuzz.fizzbuzzTree(fizzbuzz).getRoot().getData());
    }
    @Test void InsertionTest(){
        int[] ar={8,4,23,42,16,15};
        InsertionSort sortedArray=new InsertionSort();
        System.out.println(Arrays.toString(sortedArray.Insertion(ar)));
        assertEquals("[4, 8, 15, 16, 23, 42]",Arrays.toString(sortedArray.Insertion(ar)));
    }

    @Test void MergeTest(){
        int[] ar2={8,4,23,42,16,15};
        MergeSort mergeSort=new MergeSort();
        System.out.println(Arrays.toString(mergeSort.Mergesort(ar2)));
        assertEquals("[4, 8, 15, 16, 23, 42]",Arrays.toString(mergeSort.Mergesort(ar2)));
    }
    @Test void MergeOneTest(){
        int[] ar2={8};
        MergeSort mergeSort=new MergeSort();
        System.out.println(Arrays.toString(mergeSort.Mergesort(ar2)));
        assertEquals("[8]",Arrays.toString(mergeSort.Mergesort(ar2)));
    }
    @Test void MergeEmptyTest(){
        int[] ar2={};
        MergeSort mergeSort=new MergeSort();
        System.out.println(Arrays.toString(mergeSort.Mergesort(ar2)));
        assertEquals("[]",Arrays.toString(mergeSort.Mergesort(ar2)));
    }

    @Test void QuickTest(){
        int[] ar3={8,4,23,42,16,15};
        QuickSort quickSort=new QuickSort();
        quickSort.quickSort(ar3,0,ar3.length-1);
        System.out.println("sorted by quick sort algorithm= "+ Arrays.toString(ar3));
        assertEquals("[4, 8, 15, 16, 23, 42]",Arrays.toString(ar3));
    }
    @Test void QuickEmptyTest(){
        int[] ar3={};
        QuickSort quickSort=new QuickSort();
        quickSort.quickSort(ar3,0,ar3.length-1);
        System.out.println("sorted by quick sort algorithm= "+ Arrays.toString(ar3));
        assertEquals("[]",Arrays.toString(ar3));
    }
    // --------------------------- Hash map -------------------------------------------------------
    @Test void putToHashMapTest(){
        HashMap<String, String> hashMap=new HashMap<>();
        hashMap.put("java","java");
        hashMap.put("python","python");
        hashMap.put("kotlin","kotlin");
        hashMap.put("js","js");
        hashMap.put("html","html");
        hashMap.put("css","css");
        hashMap.put("php","php");
        hashMap.put("c","c");

        System.out.println("------------------ hash table test -------------------------------------");
        System.out.println("After adding 8 elements in the hash table= "+hashMap.getBucketArray());
        assertEquals(8,hashMap.getSize());
    }
    @Test void getFromHashTableTest() {
        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.put("java", "java");
        hashMap.put("python", "python");
        hashMap.put("kotlin", "kotlin");
        hashMap.put("js", "js");
        hashMap.put("html", "html");
        hashMap.put("css", "css");
        hashMap.put("php", "php");
        hashMap.put("c", "c");

        assertEquals("kotlin", hashMap.get("kotlin"));
    }

    @Test void getNullFromHashTableTest() {
        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.put("java", "java");
        hashMap.put("python", "python");
        hashMap.put("kotlin", "kotlin");
        hashMap.put("js", "js");
        hashMap.put("html", "html");
        hashMap.put("css", "css");
        hashMap.put("php", "php");
        hashMap.put("c", "c");

        assertNull(hashMap.get("anythingElse"));
    }
    @Test void getListOfTheKeysFromHashTableTest() {
        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.put("java", "java");
        hashMap.put("python", "python");
        hashMap.put("kotlin", "kotlin");
        hashMap.put("js", "js");
        hashMap.put("html", "html");
        hashMap.put("css", "css");
        hashMap.put("php", "php");
        hashMap.put("c", "c");

        assertEquals("[js, html, php, python, java, c, kotlin, css]",hashMap.keys().toString());
    }

    @Test void getFromBucketThatHasCollisionTest() {
        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.put("java", "java");
        hashMap.put("python", "python");
        hashMap.put("kotlin", "kotlin");
        hashMap.put("js", "js");
        hashMap.put("html", "html");
        hashMap.put("css", "css");
        hashMap.put("php", "php");
        hashMap.put("c", "c");

        // css located in the last index that has 3 nodes, and it's the last node in the linked list
        assertEquals("css", hashMap.get("css"));
    }
    @Test void getIndexForKeyInTheHashTableTest() {
        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.put("java", "java");
        hashMap.put("python", "python");
        hashMap.put("kotlin", "kotlin");
        hashMap.put("js", "js");
        hashMap.put("html", "html");
        hashMap.put("css", "css");
        hashMap.put("php", "php");
        hashMap.put("c", "c");

        assertEquals(19, hashMap.hash("css"));
    }

    @Test void getListOfTheKeysFromEmptyHashTableTest() {
        HashMap<String, String> hashMap2 = new HashMap<>();

        assertEquals("[]",hashMap2.keys().toString());
    }
    @Test void getIndexForKeyNotInTheHashTableTest() {
        HashMap<String, String> hashMap = new HashMap<>();
        hashMap.put("java", "java");
        hashMap.put("python", "python");
        hashMap.put("kotlin", "kotlin");
        hashMap.put("js", "js");
        hashMap.put("html", "html");
        hashMap.put("css", "css");
        hashMap.put("php", "php");
        hashMap.put("c", "c");

        assertNull(hashMap.hash("C++"));
    }
    @Test void repeatedWordTest(){
        RepeatedWord newString=new RepeatedWord();
//        System.out.println("the repeated word: "+newString.repeatedWord("Once upon a time, there was a brave princess who"));

        assertEquals("a",newString.repeatedWord("Once upon a time, there was a brave princess who"));
    }

    @Test void repeatedWordUpperCaseAndLowerCaseMatchTest(){
        RepeatedWord newString=new RepeatedWord();
//        System.out.println("the repeated word: "+newString.repeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only"));

        assertEquals("it",newString.repeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only"));
    }

    @Test void repeatedWordRemoveCommasTest(){
        RepeatedWord newString=new RepeatedWord();
//        System.out.println("the repeated word: "+newString.repeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York"));

        assertEquals("summer",newString.repeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York"));
    }
    @Test void repeatedWordNullTest(){
        RepeatedWord newString=new RepeatedWord();

        assertNull(newString.repeatedWord("Once upon a time, there was brave princess who"));
    }
    @Test void wordsCountTest(){
        RepeatedWord newString=new RepeatedWord();

        assertEquals(2,newString.wordsCount("Once upon a time, there was a brave princess who").get("a"));
    }

}
