/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challeng_6;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void addOneLastTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        String res="{1} -> NULL";
        assertEquals(res,numbers.toString());
    }

    @Test void addLastTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        String res="{1} ->{3} ->{2} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void insertBeforeTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        numbers.InsertBefore(3, 5);
        String res="{1} ->{5} ->{3} ->{2} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void insertBeforeFirstTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        numbers.InsertBefore(1, 5);
        String res="{5} ->{1} ->{3} ->{2} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void insertAfterTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        numbers.InsertAfter(3, 5);
        String res="{1} ->{3} ->{5} ->{2} -> NULL";
        assertEquals(res,numbers.toString());
    }
    @Test void insertAfterLastTest(){
        LinkedList<Integer> numbers = new LinkedList<>();
        numbers.Append(1);
        numbers.Append(3);
        numbers.Append(2);
        numbers.InsertAfter(2, 5);
        String res="{1} ->{3} ->{2} ->{5} -> NULL";
        assertEquals(res,numbers.toString());
    }

}
