/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge10;

import challenge10.pseudoQueue.pseudoQueue;
import challenge10.queue.structure.Queue;
import challenge10.stack.structure.Stack;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.function.Executable;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void stackPushTest(){
        Stack newStack=new Stack();
        newStack.push("1");
        assertEquals(1,newStack.getSize());
    }
    @Test void stackMultiplePushTest(){
        Stack newStack=new Stack();
        newStack.push("1");
        newStack.push("2");
        newStack.push("3");
        newStack.push("4");
        newStack.push("5");
        assertEquals(5,newStack.getSize());
    }
    @Test void stackPopTest() throws Exception {
        Stack newStack=new Stack();
        newStack.push("1");
        newStack.push("2");
        newStack.push("3");
        newStack.push("4");
        newStack.push("5");
        System.out.println(newStack.pop());
        assertEquals(4,newStack.getSize());
    }
    @Test void stackMultiplePopTest() throws Exception {
        Stack newStack=new Stack();
        newStack.push("1");
        newStack.push("2");
        newStack.push("3");
        newStack.push("4");
        newStack.push("5");
        System.out.println(newStack.pop());
        System.out.println(newStack.pop());
        System.out.println(newStack.pop());
        System.out.println(newStack.pop());
        System.out.println(newStack.pop());
        assertEquals(0,newStack.getSize());
    }
    @Test void stackPeekTest() throws Exception {
        Stack newStack=new Stack();
        newStack.push("1");
        newStack.push("2");
        newStack.push("3");
        newStack.push("4");
        newStack.push("5");
        System.out.println(newStack.peek());
        assertEquals("5",newStack.peek());
    }
    @Test void stackEmptyTest(){
        Stack newStack=new Stack();
        assertNull(newStack.getTop());
    }
    @Test void stackEmptyPopTest()  {
        assertThrows(Exception.class, () -> {
            Stack newStack=new Stack();
            newStack.pop();
        });
    }
    @Test void stackEmptyPeekTest(){
        assertThrows(Exception.class, () -> {
            Stack newStack=new Stack();
            String val=newStack.peek();
        });
    }
    @Test void queueEnqueueTest(){
        Queue newQueue=new Queue();
        newQueue.enqueue("1");
        assertEquals(1,newQueue.getSize());
    }
    @Test void queueEnqueueMultipleTest(){
        Queue newQueue=new Queue();
        newQueue.enqueue("1");
        newQueue.enqueue("2");
        newQueue.enqueue("3");
        newQueue.enqueue("4");
        newQueue.enqueue("5");
        assertEquals(5,newQueue.getSize());
    }
    @Test void DequeueTest() throws Exception {
        Queue newQueue=new Queue();
        newQueue.enqueue("1");
        newQueue.enqueue("2");
        newQueue.enqueue("3");
        newQueue.enqueue("4");
        newQueue.enqueue("5");
        System.out.println(newQueue.dequeue());
        assertEquals(4,newQueue.getSize());
    }
    @Test void queuePeekTest() throws Exception {
        Queue newQueue=new Queue();
        newQueue.enqueue("1");
        newQueue.enqueue("2");
        newQueue.enqueue("3");
        newQueue.enqueue("4");
        newQueue.enqueue("5");
        System.out.println(newQueue.peek());
        assertEquals("1",newQueue.peek());
    }
    @Test void DequeueMultipleTest() throws Exception {
        Queue newQueue=new Queue();
        newQueue.enqueue("1");
        newQueue.enqueue("2");
        newQueue.enqueue("3");
        newQueue.enqueue("4");
        newQueue.enqueue("5");
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.dequeue());
        assertEquals(0,newQueue.getSize());
    }
    @Test void EmptyQueueTest(){
        Queue newQueue=new Queue();
        assertNull(newQueue.getFront());
    }
    @Test void queueEmptyPeekTest(){
        assertThrows(Exception.class, () -> {
            Queue newQueue=new Queue();
            String val=newQueue.peek();
            System.out.println(val);
        });
    }
    @Test void queueEmptyDequeueTest(){
        assertThrows(Exception.class, () -> {
            Queue newQueue=new Queue();
            String val=newQueue.dequeue();
            System.out.println(val);
        });
    }
    @Test void pseudoQueueTest() throws Exception {
        pseudoQueue newQueue=new pseudoQueue();
        newQueue.enQueue("1");
        newQueue.enQueue("2");
        newQueue.enQueue("3");
        newQueue.enQueue("4");

        assertEquals("1",newQueue.getS1().getTop().getValue());
    }
    @Test void pseudoDequeueTest() throws Exception {
        pseudoQueue newQueue=new pseudoQueue();
        newQueue.enQueue("1");
        newQueue.enQueue("2");
        newQueue.enQueue("3");
        newQueue.enQueue("4");
        String last=newQueue.deQueue();
        assertEquals("1",last);
    }

}
