/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge_5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void linkedListInstantTest(){
        LinkedList<String> Animals = new LinkedList<>();
        assertNull(Animals.head);
    }
    @Test void insertTest(){
        LinkedList<String> Animals = new LinkedList<>();
        Animals.InsertNode("cat");
        Animals.InsertNode("dog");
        Animals.InsertNode("bird");
        Animals.InsertNode("horse");
        Animals.InsertNode("bear");
        Animals.InsertNode("lion");
        Animals.InsertNode("fish");
        assertNotNull(Animals);
    }
    @Test void headTest(){
        LinkedList<String> Animals = new LinkedList<>();
        Animals.InsertNode("cat");
        Animals.InsertNode("dog");
        Animals.InsertNode("bird");
        Animals.InsertNode("horse");
        Animals.InsertNode("bear");
        Animals.InsertNode("lion");
        Animals.InsertNode("fish");
        String res="fish";
        assertEquals(res,Animals.head.value);
    }
    @Test void existsTest(){
        LinkedList<String> Animals = new LinkedList<>();
        Animals.InsertNode("cat");
        Animals.InsertNode("dog");
        Animals.InsertNode("bird");
        Animals.InsertNode("horse");
        Animals.InsertNode("bear");
        Animals.InsertNode("lion");
        Animals.InsertNode("fish");
        boolean bool=true;
        assertEquals(bool,Animals.Includes("bear"));
    }
    @Test void notExistsTest(){
        LinkedList<String> Animals = new LinkedList<>();
        Animals.InsertNode("cat");
        Animals.InsertNode("dog");
        Animals.InsertNode("bird");
        Animals.InsertNode("horse");
        Animals.InsertNode("bear");
        Animals.InsertNode("lion");
        Animals.InsertNode("fish");
        boolean bool=false;
        assertEquals(bool,Animals.Includes("fox"));
    }
    @Test void toStringTest(){
        LinkedList<String> Animals = new LinkedList<>();
        Animals.InsertNode("cat");
        Animals.InsertNode("dog");
        Animals.InsertNode("bird");
        Animals.InsertNode("horse");
        Animals.InsertNode("bear");
        Animals.InsertNode("lion");
        Animals.InsertNode("fish");
        String res="{fish} ->{lion} ->{bear} ->{horse} ->{bird} ->{dog} ->{cat} -> NULL";
        assertEquals(res,Animals.toString());
    }


}
